---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "<chart_version>" # Specify the version if needed
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    adminPassword: "MyP@ssw0rd"
    persistence:
      enabled: false
