---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "6.17.4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
  values:
    adminUser: admin
    adminPassword: MyP@ssw0rd
    service:
      type: ClusterIP
    ingress:
      enabled: true
      hosts:
        - grafana.dev.barisceviz.com
    persistence:
      enabled: true
      storageClassName: "grafana-storage"
      accessModes:
        - ReadWriteOnce
      size: 10Gi
    podSecurityPolicy:
      enabled: false
