---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: backend
  namespace: flux-system
spec:
  interval: 5m
  path: "../backend"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
