---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: frontend
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/frontend
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
