---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
