---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 1h
  releaseName: istio-base
  chart:
    spec:
      chart: base
      version: "1.19.3" # Specify the desired version
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  values: {} # any values you want to override for the base
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-system
spec:
  interval: 1h
  releaseName: istio-ingress
  chart:
    spec:
      chart: gateway
      version: "1.19.3" # Specify the desired version
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  values:
    name: ingressgateway
