---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 1h
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb
  install:
    remediation:
      retries: 3
  values:
# ---
# apiVersion: metallb.io/v1beta1
# kind: IPAddressPool
# metadata:
#   name: local-network
#   namespace: metallb
# spec:
#   addresses:
#     - 192.168.178.162-192.168.178.165
# ---
# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   name: l2-local-config
#   namespace: metallb
# spec:
#   ipAddressPools:
#     - local-network
#   nodeSelectors:
#     - matchLabels:
#         kubernetes.io/hostname: local-apps-stag-worker
#     - matchLabels:
#         kubernetes.io/hostname: local-apps-stag-worker2
#
